const fs = require('fs');
const path = require('path');

const ROOT = path.resolve(__dirname, '..');
const SOURCE_DIR = path.join(ROOT, 'source');
const DIST_DIR = path.join(ROOT, 'dist');
const DIST_CSS_DIR = path.join(DIST_DIR, 'css');
const REGISTRY_DTS_PATH = path.join(DIST_DIR, 'registry.d.ts');
const PRESETS_DTS_PATH = path.join(DIST_DIR, 'presets.d.ts');
const SCHEMA_DIST_DIR = path.join(DIST_DIR, 'schema');
const THEME_SCHEMA_PATH = path.join(SOURCE_DIR, 'schema', 'theme.schema.json');
const RUNTIME_SOURCE_DIR = path.join(SOURCE_DIR, 'runtime');
const RUNTIME_DIR = path.join(ROOT, 'runtime');
const COMPILE_BRAND_THEME_SOURCE_PATH = path.join(
  RUNTIME_SOURCE_DIR,
  'compile-brand-theme.source.js'
);
const COMPILE_BRAND_THEME_MJS_PATH = path.join(RUNTIME_DIR, 'compile-brand-theme.mjs');
const COMPILE_BRAND_THEME_CJS_PATH = path.join(RUNTIME_DIR, 'compile-brand-theme.cjs');

const PRIMITIVE_DIR = path.join(SOURCE_DIR, 'primitives');
const SEMANTIC_DIR = path.join(SOURCE_DIR, 'semantic');
const COMPONENT_DIR = path.join(SOURCE_DIR, 'components');
const THEMES_DIR = path.join(SOURCE_DIR, 'themes');
const REACT_SRC_DIR = path.join(ROOT, '..', 'react', 'src');
const DOCS_SRC_DIR = path.join(ROOT, '..', '..', 'apps', 'docs', 'src');

const TOKEN_TYPE_VALUES = new Set([
  'color',
  'dimension',
  'number',
  'font-family',
  'font-weight',
  'line-height',
  'shadow',
  'duration',
  'easing',
  'transition',
  'string',
]);
const TOKEN_STATUS_VALUES = new Set(['active', 'deprecated', 'internal']);
const CSS_VAR_PATTERN = /^--ty-[a-z0-9]+(?:-[a-z0-9]+)*$/;
const SIZE_AXIS_VALUES = new Set(['sm', 'md', 'lg', 'xs', 'xl']);
const STATE_AXIS_VALUES = new Set(['hover', 'active', 'focus', 'disabled', 'checked', 'selected']);
const ALLOWED_LEAF_COMPOUNDS = ['focus-ring'];

function tokenizeLeaf(leaf) {
  const raw = leaf.split('-');
  const out = [];
  let i = 0;
  while (i < raw.length) {
    let matched = false;
    for (const compound of ALLOWED_LEAF_COMPOUNDS) {
      const cParts = compound.split('-');
      if (cParts.every((part, k) => raw[i + k] === part)) {
        out.push(compound);
        i += cParts.length;
        matched = true;
        break;
      }
    }
    if (!matched) {
      out.push(raw[i]);
      i += 1;
    }
  }
  return out;
}

function axisKindOfPart(part) {
  if (STATE_AXIS_VALUES.has(part)) return 'state';
  if (SIZE_AXIS_VALUES.has(part)) return 'size';
  return null;
}

function findLeafAxisViolation(key) {
  const lastDot = key.lastIndexOf('.');
  const leaf = lastDot === -1 ? key : key.slice(lastDot + 1);

  const parts = tokenizeLeaf(leaf);
  if (parts.length === 1) return null;

  if (parts.every((part) => axisKindOfPart(part))) return null;

  for (let i = 0; i < parts.length; i += 1) {
    const kind = axisKindOfPart(parts[i]);
    if (!kind) continue;

    const prev = i > 0 ? parts[i - 1] : null;
    const next = i + 1 < parts.length ? parts[i + 1] : null;
    const prevKind = prev ? axisKindOfPart(prev) : null;
    const nextKind = next ? axisKindOfPart(next) : null;

    if (prev === null) {
      return { reason: `${kind} axis "${parts[i]}" leads the leaf; properties must precede axes` };
    }
    if (next !== null && !nextKind) {
      return { reason: `${kind} axis "${parts[i]}" appears mid-leaf before non-axis segment "${next}"` };
    }
    if (!prevKind) {
      return { reason: `${kind} axis "${parts[i]}" must be a dot-separated segment, not glued by dash to "${prev}"` };
    }
  }

  return null;
}
const CONSUMER_FILE_EXTENSIONS = new Set(['.css', '.scss', '.ts', '.tsx']);
const GENERATED_RUNTIME_HEADER =
  '// Generated by scripts/build-runtime.js from source/runtime/compile-brand-theme.source.js.\n' +
  '// Do not edit this file directly.\n\n';

function mkdirp(dir) {
  fs.mkdirSync(dir, { recursive: true });
}

function readJson(filePath) {
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function readText(filePath) {
  return fs.readFileSync(filePath, 'utf8');
}

function writeJson(filePath, value) {
  fs.writeFileSync(filePath, JSON.stringify(value, null, 2) + '\n');
}

function normalizeTrailingNewline(value) {
  return value.replace(/\r\n/g, '\n').trimEnd() + '\n';
}

function listJsonFiles(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs
    .readdirSync(dir)
    .filter((name) => name.endsWith('.json'))
    .sort()
    .map((name) => path.join(dir, name));
}

function listSourceFiles(dir) {
  if (!fs.existsSync(dir)) return [];

  const files = [];

  for (const entry of fs.readdirSync(dir, { withFileTypes: true })) {
    const fullPath = path.join(dir, entry.name);
    if (entry.isDirectory()) {
      files.push(...listSourceFiles(fullPath));
      continue;
    }

    if (CONSUMER_FILE_EXTENSIONS.has(path.extname(entry.name))) {
      files.push(fullPath);
    }
  }

  return files.sort();
}

function listDirectories(dir) {
  if (!fs.existsSync(dir)) return [];

  return fs
    .readdirSync(dir, { withFileTypes: true })
    .filter((entry) => entry.isDirectory())
    .map((entry) => entry.name)
    .sort();
}

function basenameWithoutExt(filePath) {
  return path.basename(filePath, path.extname(filePath));
}

function isObject(value) {
  return typeof value === 'object' && value !== null && !Array.isArray(value);
}

function tokenKeyToCssVar(key) {
  return `--ty-${key.replace(/\./g, '-')}`;
}

function getComponentName(key) {
  return key.includes('.') ? key.split('.')[0] : null;
}

function titleCase(value) {
  return value
    .split(/[-.]/)
    .filter(Boolean)
    .map((segment) => segment.charAt(0).toUpperCase() + segment.slice(1))
    .join(' ');
}

function getTokenStatus(token) {
  if (token.status) {
    return token.status;
  }

  return token.category === 'primitive' ? 'internal' : 'active';
}

function getTokenGroup(token) {
  if (token.component) {
    return titleCase(token.component);
  }

  return titleCase(token.sourceFileBase || token.category);
}

function formatValidationError(title, errors) {
  return `${title}\n${errors.map((error) => `- ${error}`).join('\n')}`;
}

function lineNumberForIndex(sourceText, index) {
  let line = 1;

  for (let i = 0; i < index; i += 1) {
    if (sourceText.charCodeAt(i) === 10) {
      line += 1;
    }
  }

  return line;
}

function buildCompileBrandThemeRuntimeOutputs() {
  const source = normalizeTrailingNewline(readText(COMPILE_BRAND_THEME_SOURCE_PATH));
  const exportsBlock =
    'export { DEFAULT_BRAND_SEED_FIELDS, compileBrandTheme };\n';
  const moduleExportsBlock =
    'module.exports = {\n' +
    '  DEFAULT_BRAND_SEED_FIELDS,\n' +
    '  compileBrandTheme,\n' +
    '};\n';

  return {
    mjs: GENERATED_RUNTIME_HEADER + source + '\n' + exportsBlock,
    cjs: `'use strict';\n\n` + GENERATED_RUNTIME_HEADER + source + '\n' + moduleExportsBlock,
  };
}

function syncCompileBrandThemeRuntime(options = {}) {
  const shouldWriteArtifacts = options.write !== false;
  const outputs = buildCompileBrandThemeRuntimeOutputs();
  const mismatches = [];

  for (const [filePath, expectedContents] of [
    [COMPILE_BRAND_THEME_MJS_PATH, outputs.mjs],
    [COMPILE_BRAND_THEME_CJS_PATH, outputs.cjs],
  ]) {
    const currentContents = fs.existsSync(filePath) ? readText(filePath).replace(/\r\n/g, '\n') : null;

    if (currentContents === expectedContents) {
      continue;
    }

    if (shouldWriteArtifacts) {
      fs.writeFileSync(filePath, expectedContents);
      continue;
    }

    mismatches.push(path.relative(ROOT, filePath));
  }

  if (mismatches.length > 0) {
    throw new Error(
      formatValidationError(
        'Generated runtime files are out of date.',
        mismatches.map(
          (filePath) =>
            `${filePath} is stale. Run "pnpm --filter @tiny-design/tokens build" to regenerate runtime outputs.`
        )
      )
    );
  }
}

function resolveTokenValue(rawValue, tokenMap, stack = []) {
  if (typeof rawValue !== 'string') {
    return rawValue;
  }

  const match = rawValue.match(/^\{([^}]+)\}$/);
  if (!match) {
    return rawValue;
  }

  const refKey = match[1];
  if (stack.includes(refKey)) {
    throw new Error(`has a circular reference chain: ${[...stack, refKey].join(' -> ')}`);
  }

  const refToken = tokenMap.get(refKey);
  if (!refToken) {
    throw new Error(`references unknown token "${refKey}"`);
  }

  return resolveTokenValue(refToken.$value, tokenMap, [...stack, refKey]);
}

function toCssValue(rawValue, tokenMap) {
  if (typeof rawValue !== 'string') {
    return String(rawValue);
  }

  const match = rawValue.match(/^\{([^}]+)\}$/);
  if (!match) {
    return rawValue;
  }

  const refKey = match[1];
  if (!tokenMap.has(refKey)) {
    throw new Error(`references unknown token "${refKey}"`);
  }

  return `var(${tokenKeyToCssVar(refKey)})`;
}

function loadThemeSchemaConfig() {
  const schema = readJson(THEME_SCHEMA_PATH);

  return {
    id: schema.$id,
    requiredTopLevelKeys: new Set(schema.required || []),
    topLevelKeys: new Set(Object.keys(schema.properties || {})),
    modeValues: new Set((((schema.properties || {}).mode || {}).enum) || []),
    extendsPattern: new RegExp(((schema.properties || {}).extends || {}).pattern),
    requiredMetaKeys: new Set((((schema.$defs || {}).meta || {}).required) || []),
    metaKeys: new Set(Object.keys((((schema.$defs || {}).meta || {}).properties) || {})),
    metaIdPattern: new RegExp((((((schema.$defs || {}).meta || {}).properties || {}).id) || {}).pattern),
    metaVersionPattern: new RegExp(
      (((((schema.$defs || {}).meta || {}).properties || {}).version) || {}).pattern
    ),
    tagPattern: new RegExp(
      (((((((schema.$defs || {}).meta || {}).properties || {}).tags) || {}).items) || {}).pattern
    ),
    tokenSectionKeys: new Set(
      Object.keys(((((schema.$defs || {}).tokenSections || {}).properties) || {}))
    ),
    tokenKeyPattern: new RegExp((((schema.$defs || {}).tokenKey || {}).pattern)),
  };
}

function loadTokenFiles(dir, category) {
  return listJsonFiles(dir).flatMap((filePath) => {
    const fileData = readJson(filePath);
    const source = path.relative(ROOT, filePath);
    const sourceFileBase = basenameWithoutExt(filePath);

    if (!isObject(fileData)) {
      throw new Error(`${source} must export an object of token definitions.`);
    }

    return Object.entries(fileData).map(([key, value]) => {
      if (!isObject(value)) {
        throw new Error(`${source}: token "${key}" must be an object.`);
      }

      return {
        key,
        ...value,
        category,
        source,
        sourceFileBase,
        component: category === 'component' ? getComponentName(key) : undefined,
      };
    });
  });
}

function loadThemes() {
  return listJsonFiles(THEMES_DIR).map((filePath) => {
    const fileData = readJson(filePath);
    return {
      source: path.relative(ROOT, filePath),
      ...fileData,
    };
  });
}

function validateTokens(tokens, themeSchemaConfig) {
  const errors = [];
  const keys = new Map();
  const cssVars = new Map();
  const cssVarSet = new Set(tokens.map((token) => tokenKeyToCssVar(token.key)));
  const tokenMap = new Map(tokens.map((token) => [token.key, token]));

  for (const token of tokens) {
    const location = `${token.source}: token "${token.key}"`;
    const cssVar = tokenKeyToCssVar(token.key);

    if (!themeSchemaConfig.tokenKeyPattern.test(token.key)) {
      errors.push(`${location} does not match the theme token key pattern.`);
    }

    if (token.category === 'component') {
      const violation = findLeafAxisViolation(token.key);
      if (violation) {
        errors.push(`${location} ${violation.reason}.`);
      }
    }

    if (!('description' in token) || typeof token.description !== 'string' || token.description.trim() === '') {
      errors.push(`${location} must include a non-empty description.`);
    }

    if (!('$type' in token) || typeof token.$type !== 'string' || !TOKEN_TYPE_VALUES.has(token.$type)) {
      errors.push(`${location} has unsupported $type "${token.$type}".`);
    }

    if (!('$value' in token) || (typeof token.$value !== 'string' && typeof token.$value !== 'number')) {
      errors.push(`${location} must define $value as a string or number.`);
    }

    if (
      token.status !== undefined &&
      (typeof token.status !== 'string' || !TOKEN_STATUS_VALUES.has(token.status))
    ) {
      errors.push(`${location} has unsupported status "${token.status}".`);
    }

    if (keys.has(token.key)) {
      errors.push(`${location} duplicates key already declared in ${keys.get(token.key)}.`);
    } else {
      keys.set(token.key, token.source);
    }

    if (!CSS_VAR_PATTERN.test(cssVar)) {
      errors.push(`${location} resolves to invalid css var "${cssVar}".`);
    }

    if (cssVars.has(cssVar)) {
      errors.push(`${location} resolves to duplicate css var already declared in ${cssVars.get(cssVar)}.`);
    } else {
      cssVars.set(cssVar, token.source);
    }

    if (token.category === 'component') {
      if (!token.component) {
        errors.push(`${location} is missing a component prefix.`);
      } else if (token.component !== token.sourceFileBase) {
        errors.push(
          `${location} uses component prefix "${token.component}" but lives in ${token.sourceFileBase}.json.`
        );
      }
    }

    if (token.fallback !== undefined) {
      if (typeof token.fallback !== 'string' || !CSS_VAR_PATTERN.test(token.fallback)) {
        errors.push(`${location} has invalid fallback "${token.fallback}".`);
      } else if (!cssVarSet.has(token.fallback)) {
        errors.push(`${location} points to missing fallback "${token.fallback}".`);
      }
    }
  }

  for (const token of tokens) {
    const location = `${token.source}: token "${token.key}"`;

    try {
      resolveTokenValue(token.$value, tokenMap, [token.key]);
    } catch (error) {
      errors.push(`${location} ${error.message}.`);
    }

    const directReferenceMatch =
      typeof token.$value === 'string' ? token.$value.match(/^\{([^}]+)\}$/) : null;
    if (!directReferenceMatch) {
      continue;
    }

    const referenceToken = tokenMap.get(directReferenceMatch[1]);
    if (token.category === 'component' && referenceToken && referenceToken.category === 'primitive') {
      errors.push(
        `${location} cannot reference primitive token "${referenceToken.key}" directly; use a semantic token instead.`
      );
    }
  }

  return { errors, tokenMap };
}

function buildPresetMap(themes) {
  return themes.reduce((acc, theme) => {
    if (theme.meta && theme.meta.id) {
      acc[theme.meta.id] = theme;
    }
    return acc;
  }, {});
}

function buildRegistry(tokens, tokenMap) {
  return {
    version: 1,
    generatedAt: new Date().toISOString(),
    tokens: tokens.map((token) => ({
      key: token.key,
      cssVar: tokenKeyToCssVar(token.key),
      category: token.category,
      ...(token.component ? { component: token.component } : {}),
      type: token.$type,
      group: getTokenGroup(token),
      description: token.description || '',
      source: token.source,
      defaultValue: token.$value,
      resolvedValue: resolveTokenValue(token.$value, tokenMap, [token.key]),
      ...(token.fallback ? { fallback: token.fallback } : {}),
      status: getTokenStatus(token),
    })),
  };
}

function validateThemeSchemaDocument(theme, themeSchemaConfig) {
  const errors = [];
  const source = theme.source || 'unknown theme source';

  if (!isObject(theme)) {
    return [`${source}: theme document must be an object.`];
  }

  for (const key of Object.keys(theme)) {
    if (!themeSchemaConfig.topLevelKeys.has(key) && key !== 'source') {
      errors.push(`${source}: field "${key}" is not allowed by the theme schema.`);
    }
  }

  for (const requiredKey of themeSchemaConfig.requiredTopLevelKeys) {
    if (!Object.prototype.hasOwnProperty.call(theme, requiredKey)) {
      errors.push(`${source}: missing required field "${requiredKey}".`);
    }
  }

  if (theme.$schema !== undefined && typeof theme.$schema !== 'string') {
    errors.push(`${source}: $schema must be a string.`);
  }

  if (!isObject(theme.meta)) {
    errors.push(`${source}: meta must be an object.`);
  } else {
    for (const key of Object.keys(theme.meta)) {
      if (!themeSchemaConfig.metaKeys.has(key)) {
        errors.push(`${source}: meta.${key} is not allowed by the theme schema.`);
      }
    }

    for (const requiredKey of themeSchemaConfig.requiredMetaKeys) {
      if (!Object.prototype.hasOwnProperty.call(theme.meta, requiredKey)) {
        errors.push(`${source}: meta.${requiredKey} is required.`);
      }
    }

    if (
      theme.meta.id !== undefined &&
      (typeof theme.meta.id !== 'string' || !themeSchemaConfig.metaIdPattern.test(theme.meta.id))
    ) {
      errors.push(`${source}: meta.id "${theme.meta.id}" does not match the schema pattern.`);
    }

    if (theme.meta.name !== undefined) {
      if (typeof theme.meta.name !== 'string' || theme.meta.name.length < 1 || theme.meta.name.length > 120) {
        errors.push(`${source}: meta.name must be a non-empty string up to 120 characters.`);
      }
    }

    if (theme.meta.author !== undefined) {
      if (
        typeof theme.meta.author !== 'string' ||
        theme.meta.author.length < 1 ||
        theme.meta.author.length > 120
      ) {
        errors.push(`${source}: meta.author must be a non-empty string up to 120 characters.`);
      }
    }

    if (theme.meta.description !== undefined) {
      if (typeof theme.meta.description !== 'string' || theme.meta.description.length > 500) {
        errors.push(`${source}: meta.description must be a string up to 500 characters.`);
      }
    }

    if (
      theme.meta.version !== undefined &&
      (typeof theme.meta.version !== 'string' ||
        !themeSchemaConfig.metaVersionPattern.test(theme.meta.version))
    ) {
      errors.push(`${source}: meta.version "${theme.meta.version}" is not valid semver.`);
    }

    if (theme.meta.schemaVersion !== undefined && theme.meta.schemaVersion !== 1) {
      errors.push(`${source}: meta.schemaVersion must equal 1.`);
    }

    if (theme.meta.tags !== undefined) {
      if (!Array.isArray(theme.meta.tags)) {
        errors.push(`${source}: meta.tags must be an array.`);
      } else {
        const tagSet = new Set();

        if (theme.meta.tags.length > 20) {
          errors.push(`${source}: meta.tags cannot contain more than 20 items.`);
        }

        for (const tag of theme.meta.tags) {
          if (typeof tag !== 'string' || !themeSchemaConfig.tagPattern.test(tag)) {
            errors.push(`${source}: meta.tags contains invalid tag "${tag}".`);
            continue;
          }

          if (tagSet.has(tag)) {
            errors.push(`${source}: meta.tags contains duplicate tag "${tag}".`);
            continue;
          }

          tagSet.add(tag);
        }
      }
    }
  }

  if (typeof theme.mode !== 'string' || !themeSchemaConfig.modeValues.has(theme.mode)) {
    errors.push(`${source}: mode must be one of ${Array.from(themeSchemaConfig.modeValues).join(', ')}.`);
  }

  if (
    theme.extends !== undefined &&
    (typeof theme.extends !== 'string' || !themeSchemaConfig.extendsPattern.test(theme.extends))
  ) {
    errors.push(`${source}: extends "${theme.extends}" does not match the schema pattern.`);
  }

  if (!isObject(theme.tokens)) {
    errors.push(`${source}: tokens must be an object.`);
  } else {
    for (const key of Object.keys(theme.tokens)) {
      if (!themeSchemaConfig.tokenSectionKeys.has(key)) {
        errors.push(`${source}: tokens.${key} is not allowed by the theme schema.`);
      }
    }

    for (const sectionName of themeSchemaConfig.tokenSectionKeys) {
      const section = theme.tokens[sectionName];

      if (section === undefined) continue;

      if (!isObject(section)) {
        errors.push(`${source}: tokens.${sectionName} must be an object.`);
        continue;
      }

      for (const [key, value] of Object.entries(section)) {
        if (!themeSchemaConfig.tokenKeyPattern.test(key)) {
          errors.push(`${source}: tokens.${sectionName}.${key} does not match the schema token key pattern.`);
        }

        if (typeof value === 'string') {
          if (value.length === 0) {
            errors.push(`${source}: tokens.${sectionName}.${key} cannot be an empty string.`);
          }
          continue;
        }

        if (typeof value !== 'number') {
          errors.push(`${source}: tokens.${sectionName}.${key} must be a string or number.`);
        }
      }
    }
  }

  return errors;
}

function validateThemeRegistryUsage(themes, tokens, themeSchemaConfig) {
  const errors = [];
  const warnings = [];
  const tokenMap = new Map(tokens.map((token) => [token.key, token]));
  const themeIdSources = new Map();
  const presetMap = buildPresetMap(themes);

  for (const theme of themes) {
    const source = theme.source || 'unknown theme source';
    errors.push(...validateThemeSchemaDocument(theme, themeSchemaConfig));

    const themeId = theme.meta && theme.meta.id;
    if (themeId) {
      if (themeIdSources.has(themeId)) {
        errors.push(
          `${source}: meta.id "${themeId}" duplicates theme id already declared in ${themeIdSources.get(themeId)}.`
        );
      } else {
        themeIdSources.set(themeId, source);
      }
    }
  }

  function validatePresetChain(theme, visited = new Set()) {
    const source = theme.source || 'unknown theme source';

    if (!theme.extends) return;

    const preset = presetMap[theme.extends];
    if (!preset) {
      errors.push(`${source}: extends unknown preset "${theme.extends}".`);
      return;
    }

    if (visited.has(theme.extends)) {
      errors.push(`${source}: extends chain for "${theme.extends}" is circular.`);
      return;
    }

    visited.add(theme.extends);
    validatePresetChain(preset, visited);
    visited.delete(theme.extends);
  }

  function validateThemeSection(theme, sectionName, expectedCategory) {
    const source = theme.source || 'unknown theme source';
    const section = theme.tokens && theme.tokens[sectionName];

    if (!isObject(section)) return;

    for (const [key, value] of Object.entries(section)) {
      const registryToken = tokenMap.get(key);

      if (!registryToken) {
        errors.push(`${source}: tokens.${sectionName}.${key} is not present in the token registry.`);
        continue;
      }

      if (registryToken.category !== expectedCategory) {
        errors.push(
          `${source}: tokens.${sectionName}.${key} belongs to category "${registryToken.category}", not "${expectedCategory}".`
        );
      }

      if (getTokenStatus(registryToken) === 'internal') {
        errors.push(`${source}: tokens.${sectionName}.${key} is internal and cannot be authored in themes.`);
      }

      if (getTokenStatus(registryToken) === 'deprecated') {
        warnings.push(`${source}: tokens.${sectionName}.${key} is deprecated.`);
      }

      if (typeof value !== 'string') continue;

      const referenceMatch = value.match(/^\{([^}]+)\}$/);
      if (!referenceMatch) continue;

      if (!tokenMap.has(referenceMatch[1])) {
        errors.push(`${source}: tokens.${sectionName}.${key} references unknown token "${referenceMatch[1]}".`);
        continue;
      }

      const referenceToken = tokenMap.get(referenceMatch[1]);
      if (referenceToken && (referenceToken.category === 'primitive' || getTokenStatus(referenceToken) === 'internal')) {
        errors.push(
          `${source}: tokens.${sectionName}.${key} cannot reference internal primitive token "${referenceMatch[1]}".`
        );
      }
    }
  }

  for (const theme of themes) {
    validatePresetChain(theme);
    validateThemeSection(theme, 'semantic', 'semantic');
    validateThemeSection(theme, 'components', 'component');
  }

  return { errors, warnings };
}

function buildThemeCss(tokens, cssValues, tokenMap, overrides, selector) {
  const lines = [`${selector} {`];

  for (const token of tokens) {
    const overrideValue = overrides[token.key];
    const value = overrideValue !== undefined ? toCssValue(overrideValue, tokenMap) : cssValues.get(token.key);
    lines.push(`  ${tokenKeyToCssVar(token.key)}: ${value};`);
  }

  lines.push('}');
  lines.push('');

  return lines.join('\n');
}

function buildBaseThemeCss(tokens, cssValues, tokenMap, lightTheme, darkTheme) {
  const lightOverrides = {
    ...((lightTheme && lightTheme.tokens && lightTheme.tokens.semantic) || {}),
    ...((lightTheme && lightTheme.tokens && lightTheme.tokens.components) || {}),
  };
  const darkOverrides = {
    ...((darkTheme && darkTheme.tokens && darkTheme.tokens.semantic) || {}),
    ...((darkTheme && darkTheme.tokens && darkTheme.tokens.components) || {}),
  };

  const parts = [];
  parts.push(buildThemeCss(tokens, cssValues, tokenMap, lightOverrides, ':root'));
  parts.push(buildThemeCss(tokens, cssValues, tokenMap, darkOverrides, "[data-tiny-theme='dark']"));
  parts.push('@media (prefers-color-scheme: dark) {');
  parts.push(buildThemeCss(tokens, cssValues, tokenMap, darkOverrides, "  [data-tiny-theme='system']").trimEnd());
  parts.push('}');
  parts.push('');

  return parts.join('\n');
}

function buildSliceCss(tokens, cssValues, tokenMap, lightTheme, darkTheme) {
  if (tokens.length === 0) return '';
  return buildBaseThemeCss(tokens, cssValues, tokenMap, lightTheme, darkTheme);
}

const SLICE_SCAN_SKIP_DIRS = new Set(['__tests__', '__snapshots__', 'demo']);

function listSliceScanFiles(dirPath) {
  if (!fs.existsSync(dirPath)) return [];
  const result = [];
  for (const entry of fs.readdirSync(dirPath, { withFileTypes: true })) {
    if (SLICE_SCAN_SKIP_DIRS.has(entry.name)) continue;
    const full = path.join(dirPath, entry.name);
    if (entry.isDirectory()) {
      result.push(...listSliceScanFiles(full));
    } else if (CONSUMER_FILE_EXTENSIONS.has(path.extname(entry.name))) {
      result.push(full);
    }
  }
  return result;
}

function listReactComponentDirs() {
  if (!fs.existsSync(REACT_SRC_DIR)) return [];
  return listDirectories(REACT_SRC_DIR).filter(
    (name) => !name.startsWith('_') && name !== 'style' && name !== 'locale'
  );
}

function extractStyleEntryDeps(dirName, namespacesWithStyles) {
  const styleEntryPath = path.join(REACT_SRC_DIR, dirName, 'style', 'index.tsx');
  if (!fs.existsSync(styleEntryPath)) return new Set();

  const sourceText = readText(styleEntryPath);
  const importRegex = /from\s+['"]([^'"]+)['"]|import\s+['"]([^'"]+)['"]/g;
  const deps = new Set();
  let match;

  while ((match = importRegex.exec(sourceText)) !== null) {
    const importPath = match[1] || match[2];
    const styleDepMatch = importPath.match(/^\.\.\/\.\.\/([^/]+)\/style/);
    if (styleDepMatch && namespacesWithStyles.has(styleDepMatch[1])) {
      deps.add(styleDepMatch[1]);
    }
  }

  return deps;
}

function computeSliceManifest(allTokens) {
  const componentTokens = allTokens.filter((token) => token.category === 'component');
  const tokensByNamespace = new Map();
  for (const token of componentTokens) {
    if (!token.component) continue;
    if (!tokensByNamespace.has(token.component)) {
      tokensByNamespace.set(token.component, []);
    }
    tokensByNamespace.get(token.component).push(token);
  }

  const varToNamespace = new Map();
  for (const token of componentTokens) {
    if (token.component) {
      varToNamespace.set(tokenKeyToCssVar(token.key), token.component);
    }
  }

  const reactDirs = listReactComponentDirs();
  const namespacesWithStyles = new Set(reactDirs);

  const directDeps = new Map();
  for (const dirName of reactDirs) {
    const dirPath = path.join(REACT_SRC_DIR, dirName);
    const deps = new Set();

    for (const filePath of listSliceScanFiles(dirPath)) {
      const sourceText = readText(filePath);
      for (const reference of extractTyVarReferences(sourceText)) {
        const namespace = varToNamespace.get(reference.name);
        if (namespace) deps.add(namespace);
      }
    }

    for (const styleDep of extractStyleEntryDeps(dirName, namespacesWithStyles)) {
      deps.add(styleDep);
    }

    directDeps.set(dirName, deps);
  }

  const closure = new Map();
  for (const dirName of directDeps.keys()) {
    const visited = new Set();
    const queue = [...(directDeps.get(dirName) || [])];
    while (queue.length > 0) {
      const namespace = queue.shift();
      if (visited.has(namespace)) continue;
      visited.add(namespace);
      const nsDeps = directDeps.get(namespace);
      if (nsDeps) {
        for (const next of nsDeps) {
          if (!visited.has(next)) queue.push(next);
        }
      }
    }
    closure.set(dirName, visited);
  }

  const manifest = {};
  const tokenSliceNames = new Set(tokensByNamespace.keys());
  for (const [dirName, namespaceSet] of closure.entries()) {
    const sliceNames = Array.from(namespaceSet)
      .filter((namespace) => tokenSliceNames.has(namespace))
      .sort();
    if (sliceNames.length === 0) continue;
    manifest[dirName] = sliceNames;
  }

  return { tokensByNamespace, manifest };
}

function buildRegistryDts() {
  return `export type TokenCategory = 'primitive' | 'semantic' | 'component';
export type TokenType =
  | 'color'
  | 'dimension'
  | 'number'
  | 'font-family'
  | 'font-weight'
  | 'line-height'
  | 'shadow'
  | 'duration'
  | 'easing'
  | 'transition'
  | 'string';

export interface TokenRegistryEntry {
  key: string;
  cssVar: string;
  category: TokenCategory;
  component?: string;
  type: TokenType;
  group: string;
  description: string;
  source: string;
  defaultValue: string | number;
  resolvedValue: string | number;
  fallback?: string;
  status: 'active' | 'deprecated' | 'internal';
}

export interface TokenRegistryDocument {
  version: number;
  generatedAt: string;
  tokens: TokenRegistryEntry[];
}
`;
}

function buildPresetsDts(presets) {
  const ids = Object.keys(presets);
  const presetUnion = ids.length > 0 ? ids.map((id) => `'${id}'`).join(' | ') : 'string';

  return `export type PresetThemeId = ${presetUnion};

export interface ThemeDocumentMeta {
  id?: string;
  name?: string;
  author?: string;
  description?: string;
  version?: string;
  schemaVersion?: number;
  tags?: string[];
}

export interface ThemeDocumentTokens {
  semantic?: Record<string, string | number>;
  components?: Record<string, string | number>;
}

export interface ThemeDocument {
  $schema?: string;
  meta?: ThemeDocumentMeta;
  mode: 'light' | 'dark' | 'system';
  extends?: string;
  tokens?: ThemeDocumentTokens;
}

declare const presets: Record<PresetThemeId, ThemeDocument>;
export default presets;
`;
}

function collectLocalCssVars(files) {
  const definedVars = new Set();

  for (const filePath of files) {
    const sourceText = fs.readFileSync(filePath, 'utf8');
    const definitionRegex = /--ty-[a-z0-9-]+(?=['"]?\s*:)/g;
    let match;

    while ((match = definitionRegex.exec(sourceText)) !== null) {
      definedVars.add(match[0]);
    }
  }

  return definedVars;
}

function extractTyVarReferences(sourceText) {
  const references = [];
  const referenceRegex = /var\(\s*(--ty-[a-z0-9-]+)\s*(,|\))/g;
  let match;

  while ((match = referenceRegex.exec(sourceText)) !== null) {
    references.push({
      name: match[1],
      hasFallback: match[2] === ',',
      index: match.index,
    });
  }

  return references;
}

function collectOverridePrefixes(tokens) {
  const prefixes = new Set(
    tokens.filter((token) => token.category === 'component' && token.component).map((token) => token.component)
  );

  for (const directoryName of listDirectories(REACT_SRC_DIR)) {
    prefixes.add(directoryName);
  }

  return prefixes;
}

function isComponentOverrideHook(cssVar, hasFallback, overridePrefixes) {
  if (!hasFallback) return false;

  const body = cssVar.replace(/^--ty-/, '');
  const parts = body.split('-');

  for (let i = parts.length - 1; i >= 1; i -= 1) {
    const prefix = parts.slice(0, i).join('-');
    if (overridePrefixes.has(prefix)) {
      return true;
    }
  }

  return false;
}

function validateConsumerContracts(tokens) {
  const registryVars = new Set(tokens.map((token) => tokenKeyToCssVar(token.key)));
  const consumerFiles = [...listSourceFiles(REACT_SRC_DIR), ...listSourceFiles(DOCS_SRC_DIR)];
  const definedVars = collectLocalCssVars(consumerFiles);
  const overridePrefixes = collectOverridePrefixes(tokens);
  const usedRegistryVars = new Set();
  const errors = [];

  for (const filePath of consumerFiles) {
    const sourceText = fs.readFileSync(filePath, 'utf8');
    const relativePath = path.relative(ROOT, filePath);

    for (const reference of extractTyVarReferences(sourceText)) {
      if (registryVars.has(reference.name)) {
        usedRegistryVars.add(reference.name);
        continue;
      }

      if (definedVars.has(reference.name)) {
        continue;
      }

      if (isComponentOverrideHook(reference.name, reference.hasFallback, overridePrefixes)) {
        continue;
      }

      errors.push(
        `${relativePath}:${lineNumberForIndex(sourceText, reference.index)} references unknown token var "${reference.name}".`
      );
    }
  }

  if (errors.length > 0) {
    throw new Error(formatValidationError('Consumer token contract validation failed.', errors));
  }

  return {
    filesChecked: consumerFiles.length,
    usedRegistryVars: usedRegistryVars.size,
    totalRegistryVars: registryVars.size,
  };
}

function buildRuntimeTokens(options = {}) {
  const shouldWriteArtifacts = options.write !== false;
  const shouldValidateConsumers = options.verifyConsumers !== false;
  const themeSchemaConfig = loadThemeSchemaConfig();
  const actionLabel = shouldWriteArtifacts ? 'Building runtime tokens...' : 'Validating runtime tokens...';

  console.log(`${actionLabel}\n`);
  syncCompileBrandThemeRuntime({ write: shouldWriteArtifacts });

  const primitiveTokens = loadTokenFiles(PRIMITIVE_DIR, 'primitive');
  const semanticTokens = loadTokenFiles(SEMANTIC_DIR, 'semantic');
  const componentTokens = loadTokenFiles(COMPONENT_DIR, 'component');
  const allTokens = [...primitiveTokens, ...semanticTokens, ...componentTokens];
  const tokenValidation = validateTokens(allTokens, themeSchemaConfig);

  if (tokenValidation.errors.length > 0) {
    throw new Error(formatValidationError('Token validation failed.', tokenValidation.errors));
  }

  const themes = loadThemes();
  const themeValidation = validateThemeRegistryUsage(themes, allTokens, themeSchemaConfig);
  if (themeValidation.errors.length > 0) {
    throw new Error(formatValidationError('Theme validation failed.', themeValidation.errors));
  }

  if (themeValidation.warnings.length > 0) {
    console.warn(formatValidationError('Theme validation warnings.', themeValidation.warnings));
  }

  const tokenMap = tokenValidation.tokenMap;
  const cssValues = new Map(allTokens.map((token) => [token.key, toCssValue(token.$value, tokenMap)]));
  const registry = buildRegistry(allTokens, tokenMap);
  const lightTheme = themes.find((theme) => theme.mode === 'light');
  const darkTheme = themes.find((theme) => theme.mode === 'dark');
  const presets = buildPresetMap(themes);

  if (shouldValidateConsumers) {
    const consumerSummary = validateConsumerContracts(allTokens);
    console.log(
      `  consumer contract check (${consumerSummary.filesChecked} files, ${consumerSummary.usedRegistryVars}/${consumerSummary.totalRegistryVars} registry vars referenced)`
    );
  }

  if (!shouldWriteArtifacts) {
    console.log('\nRuntime tokens validated.');
    return { registry, presets };
  }

  const lightThemeOverrides = {
    ...((lightTheme && lightTheme.tokens && lightTheme.tokens.semantic) || {}),
    ...((lightTheme && lightTheme.tokens && lightTheme.tokens.components) || {}),
  };
  const darkThemeOverrides = {
    ...((darkTheme && darkTheme.tokens && darkTheme.tokens.semantic) || {}),
    ...((darkTheme && darkTheme.tokens && darkTheme.tokens.components) || {}),
  };
  const lightCss = buildThemeCss(allTokens, cssValues, tokenMap, lightThemeOverrides, ':root');
  const darkCss = buildThemeCss(allTokens, cssValues, tokenMap, darkThemeOverrides, "[data-tiny-theme='dark']");
  const baseCss = buildBaseThemeCss(allTokens, cssValues, tokenMap, lightTheme, darkTheme);

  const primitiveTier = allTokens.filter((token) => token.category === 'primitive');
  const semanticTier = allTokens.filter((token) => token.category === 'semantic');
  const foundationCss = buildSliceCss(primitiveTier, cssValues, tokenMap, lightTheme, darkTheme);
  const semanticCss = buildSliceCss(semanticTier, cssValues, tokenMap, lightTheme, darkTheme);

  const { tokensByNamespace, manifest } = computeSliceManifest(allTokens);

  mkdirp(DIST_CSS_DIR);
  mkdirp(SCHEMA_DIST_DIR);
  const componentsDir = path.join(DIST_CSS_DIR, 'components');
  mkdirp(componentsDir);
  writeJson(path.join(DIST_DIR, 'registry.json'), registry);
  writeJson(path.join(DIST_DIR, 'presets.json'), presets);
  fs.writeFileSync(path.join(DIST_CSS_DIR, 'light.css'), lightCss);
  fs.writeFileSync(path.join(DIST_CSS_DIR, 'dark.css'), darkCss);
  fs.writeFileSync(path.join(DIST_CSS_DIR, 'base.css'), baseCss);
  fs.writeFileSync(path.join(DIST_CSS_DIR, 'foundation.css'), foundationCss);
  fs.writeFileSync(path.join(DIST_CSS_DIR, 'semantic.css'), semanticCss);

  for (const [namespace, namespaceTokens] of tokensByNamespace.entries()) {
    const sliceCss = buildSliceCss(namespaceTokens, cssValues, tokenMap, lightTheme, darkTheme);
    fs.writeFileSync(path.join(componentsDir, `${namespace}.css`), sliceCss);
  }

  writeJson(path.join(DIST_CSS_DIR, 'component-deps.json'), manifest);

  fs.writeFileSync(REGISTRY_DTS_PATH, buildRegistryDts());
  fs.writeFileSync(PRESETS_DTS_PATH, buildPresetsDts(presets));
  fs.copyFileSync(THEME_SCHEMA_PATH, path.join(SCHEMA_DIST_DIR, 'theme.schema.json'));

  console.log('  dist/registry.json');
  console.log('  dist/registry.d.ts');
  console.log('  dist/presets.json');
  console.log('  dist/presets.d.ts');
  console.log('  dist/schema/theme.schema.json');
  console.log('  dist/css/light.css');
  console.log('  dist/css/dark.css');
  console.log('  dist/css/base.css');
  console.log('  dist/css/foundation.css');
  console.log('  dist/css/semantic.css');
  console.log(`  dist/css/components/*.css (${tokensByNamespace.size} slices)`);
  console.log(`  dist/css/component-deps.json (${Object.keys(manifest).length} dirs)`);
  console.log('\nRuntime tokens done.');

  return { registry, presets };
}

function parseCliArgs(argv) {
  return {
    write: !argv.includes('--validate-only'),
    verifyConsumers: !argv.includes('--no-consumer-check'),
  };
}

module.exports = { buildRuntimeTokens };

if (require.main === module) {
  const cliOptions = parseCliArgs(process.argv.slice(2));

  try {
    buildRuntimeTokens(cliOptions);
  } catch (err) {
    console.error(err);
    process.exit(1);
  }
}
