import type { ThemeEditorSeedGroup } from './types';

export const SEED_COLOR_GROUPS: ThemeEditorSeedGroup[] = [
  {
    title: 'Brand Core',
    description: 'Primary, accent, and supporting brand surfaces.',
    tier: 'core',
    fields: [
      { key: 'primary', label: 'Primary' },
      { key: 'primaryForeground', label: 'On Primary' },
      { key: 'secondary', label: 'Secondary' },
      { key: 'secondaryForeground', label: 'On Secondary' },
      { key: 'accent', label: 'Accent' },
      { key: 'accentForeground', label: 'On Accent' },
    ],
  },
  {
    title: 'Feedback States',
    description: 'Semantic status hues that propagate through alerts, tags, and feedback UI.',
    tier: 'core',
    fields: [
      { key: 'success', label: 'Success' },
      { key: 'successForeground', label: 'On Success' },
      { key: 'info', label: 'Info' },
      { key: 'infoForeground', label: 'On Info' },
      { key: 'warning', label: 'Warning' },
      { key: 'warningForeground', label: 'On Warning' },
      { key: 'danger', label: 'Danger' },
      { key: 'dangerForeground', label: 'On Danger' },
    ],
  },
  {
    title: 'Surfaces & Text',
    description: 'Page, card, popover, and muted surfaces plus their text companions.',
    tier: 'core',
    fields: [
      { key: 'base', label: 'Page' },
      { key: 'baseForeground', label: 'On Page' },
      { key: 'card', label: 'Card' },
      { key: 'cardForeground', label: 'On Card' },
      { key: 'popover', label: 'Popover' },
      { key: 'popoverForeground', label: 'On Popover' },
      { key: 'muted', label: 'Muted' },
      { key: 'mutedForeground', label: 'On Muted' },
    ],
  },
  {
    title: 'Lines & Focus',
    description: 'Borders, field chrome, and the interaction ring seed.',
    tier: 'core',
    fields: [
      { key: 'border', label: 'Border' },
      { key: 'input', label: 'Input' },
      { key: 'ring', label: 'Ring' },
    ],
  },
  {
    title: 'Data Visualization',
    description: 'Chart palette seeds for data-heavy views.',
    tier: 'advanced',
    fields: [
      { key: 'chart1', label: 'Series 1' },
      { key: 'chart2', label: 'Series 2' },
      { key: 'chart3', label: 'Series 3' },
      { key: 'chart4', label: 'Series 4' },
      { key: 'chart5', label: 'Series 5' },
    ],
  },
  {
    title: 'Sidebar Shell',
    description: 'Dedicated app-shell seeds for navigation-heavy layouts.',
    tier: 'advanced',
    fields: [
      { key: 'sidebar', label: 'Sidebar' },
      { key: 'sidebarForeground', label: 'On Sidebar' },
      { key: 'sidebarPrimary', label: 'Sidebar Primary' },
      { key: 'sidebarPrimaryForeground', label: 'On Sidebar Primary' },
      { key: 'sidebarAccent', label: 'Sidebar Accent' },
      { key: 'sidebarAccentForeground', label: 'On Sidebar Accent' },
      { key: 'sidebarBorder', label: 'Sidebar Border' },
      { key: 'sidebarRing', label: 'Sidebar Ring' },
    ],
  },
];

export const FONT_OPTIONS = [
  'ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif',
  '"Instrument Sans", "Inter", system-ui, sans-serif',
  '"Inter", system-ui, sans-serif',
  '"Geist", system-ui, sans-serif',
  '"DM Sans", system-ui, sans-serif',
  '"Plus Jakarta Sans", system-ui, sans-serif',
  '"Outfit", system-ui, sans-serif',
  '"Poppins", system-ui, sans-serif',
  '"Montserrat", system-ui, sans-serif',
  '"IBM Plex Sans", system-ui, sans-serif',
  '"Manrope", system-ui, sans-serif',
  '"Open Sans", "Helvetica Neue", Arial, sans-serif',
  '"Roboto", "Helvetica Neue", Arial, sans-serif',
  '"Quicksand", system-ui, sans-serif',
  '"Antic", system-ui, sans-serif',
  '"Oxanium", system-ui, sans-serif',
  '"Architects Daughter", "Comic Sans MS", cursive, sans-serif',
  '"Source Serif 4", Georgia, serif',
  '"Merriweather", Georgia, serif',
  '"Libre Baskerville", Georgia, serif',
];

export const MONO_OPTIONS = [
  'ui-monospace, "SFMono-Regular", Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace',
  '"JetBrains Mono", "SFMono-Regular", monospace',
  '"Geist Mono", "SFMono-Regular", monospace',
  '"IBM Plex Mono", "SFMono-Regular", monospace',
  '"Fira Code", "SFMono-Regular", monospace',
  '"Source Code Pro", "SFMono-Regular", monospace',
  '"Courier New", monospace',
];
